# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Unlock an R Package Enviroment and Assign an Object to the R Package Environment
#'
#' Of unlockEnvironment, unlock a non-base package environment.  Note: R package base is unlocked (by design)
#'
#' @param env Environment. Default none. Required.
#' @return Of unlockEnvironment, Logical.  TRUE if this package environment has been successfully unlocked. FALSE otherwise.
#' @author Willem Ligtenberg is the author of unlockEnvironment
#' @references
#' \cite{unlockEnvironment function
#' \url{https://github.com/openanalytics/Rango/blob/adc99e077b71c8c6826cabb7ff1266050898718a/Rango/src/unlockEnvironment.cpp}
#' }
#' @references
#' \cite{envir.c in the R 2.15.1 source (still in R 3.3.1)
#' \url{https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/main/envir.c}
#' }
#' @export
unlockEnvironment <- function(env) {
    .Call('_econModel_unlockEnvironment', PACKAGE = 'econModel', env)
}

