# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' unlock an R package on the R search() path
#'
#' Note: R package base is unlocked by design
#'
#' @param env environment
#' @author Willem Ligtenberg
#' @references
#' \cite{unlockEnvironment function
#' \url{https://github.com/openanalytics/Rango/blob/adc99e077b71c8c6826cabb7ff1266050898718a/Rango/src/unlockEnvironment.cpp}
#' }
#' @references
#' \cite{envir.c in the R 2.15.1 source (still in R 3.3.1)
#' \url{https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/main/envir.c}
#' }
#' @examples
#' \dontrun{
#' library(econModel)
#' unlockEnvironment(as.environment(2))
#' }
#' @export
unlockEnvironment <- function(env) {
    .Call('_econModel_unlockEnvironment', PACKAGE = 'econModel', env)
}

